[package]
name = "block-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.8.18", features = ["sha3-keccak"] }
alloy-provider = {version = "0.9.2", features = ["reqwest"] }
alloy-rpc-types = "0.9.2"
alloy-transport = "0.9.2"
bincode = "1.3.3"
clap = { version = "4.5.3", features = ["derive"] }
eyre = "0.6.12"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
reth-chainspec = { git = "https://github.com/paradigmxyz/reth", default-features = false }
reth-client = { path = "../reth-client" }
reth-ethereum-consensus = { git = "https://github.com/paradigmxyz/reth", default-features = false }
reth-evm = { git = "https://github.com/paradigmxyz/reth", default-features = false }
reth-evm-ethereum = { git = "https://github.com/paradigmxyz/reth", default-features = false }
reth-primitives = { git = "https://github.com/paradigmxyz/reth", features = ["alloy-compat", "std"] }
reth-storage-errors = { git = "https://github.com/paradigmxyz/reth", default-features = false }
reth-trie = { git = "https://github.com/paradigmxyz/reth", default-features = false }
revm = "19.3.0"
revm-primitives = { version = "15.1.0"}
thiserror = "2.0.11"
tokio = {version ="1.43.0", features = ["rt", "rt-multi-thread"] }
tracing = "0.1.41"
url = "2.5.4"
