[package]
name = "block-downloader"
version.workspace = true
edition.workspace = true

[dependencies]
thiserror.workspace = true
serde_json.workspace = true
url.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

# workspace
reth-client.workspace = true

# reth
reth-primitives = { workspace = true }
reth-storage-errors.workspace = true
reth-trie.workspace = true
reth-execution-types.workspace = true
reth-errors.workspace = true
reth-chainspec.workspace = true
reth-revm.workspace = true
reth-evm.workspace = true
reth-evm-ethereum.workspace = true
reth-ethereum-consensus.workspace = true

# revm
revm.workspace = true
revm-primitives.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-rlp.workspace = true
alloy-provider.workspace = true
alloy-transport.workspace = true
itertools.workspace = true
alloy-rpc-types.workspace = true

bincode.workspace = true
clap.workspace = true
eyre.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
