[package]
name = "block-downloader"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-consensus = { version = "0.4.2" }
alloy-primitives = { version = "0.8.18", features = ["sha3-keccak"] }
alloy-provider = { version = "0.4.2", default-features = false, features = ["reqwest", "reqwest-rustls-tls"] }
alloy-rpc-types = { version = "0.4.2", default-features = false, features = ["eth"] }
alloy-transport = "0.4.2"
bincode = "1.3.3"
clap = { version = "4.5.3", features = ["derive"] }
eyre = "0.6.12"
reth-chainspec = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false }
reth-client = { path = "../reth-client" }
reth-ethereum-consensus = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false }
reth-evm = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false }
reth-evm-ethereum = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false, features = ["std"] }
reth-primitives = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false, features = ["alloy-compat", "std"] }
reth-storage-errors = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false }
reth-trie = { git = "https://github.com/risc0/reth", branch = "p1.1.0_zstd", default-features = false }
revm = { version ="14.0.0", default-features = false }
revm-primitives = { version = "9.0.0", default-features = false, features = ["serde", "std"] }
thiserror = "2.0.11"
tokio = {version ="1.43.0", features = ["rt", "rt-multi-thread"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.4"
