[workspace]
members = [
    "block-downloader",
    "eval",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
alloy-provider = { version = "0.3", default-features = false, features = ["reqwest", "reqwest-rustls-tls"] }
anyhow = "1.0.95"
bincode = "1.3.3"
clap = { version = "4.5.3", features = ["derive"] }
eyre = "0.6.12"
itertools = "0.14.0"
rlp = "0.6.1"
rsp-client-executor = { git = "https://github.com/succinctlabs/rsp/", rev = "249b34e" }
rsp-host-executor = { git = "https://github.com/succinctlabs/rsp/", rev = "249b34e" }
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_json = "1.0.94"
thiserror = "2.0.11"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.18", features = ["env-filter"] }
url = "2.5.4"

# workspace
block-downloader = { path = "block-downloader" }

[profile.dev]
opt-level = 3

[profile.dev.build-override]
opt-level = 3

[profile.release]
opt-level = 3
lto = true

[profile.fast]
inherits = "release"
debug = true
debug-assertions = true

[profile.release.build-override]
opt-level = 3
