[package]
name = "zkvm-benchmarks-eval"
version = "0.0.1"
edition = "2021"

[build-dependencies]
vergen-git2 = { version = "1.0.0", features = ["build"] }


[dependencies]
reth-client = { path = "../reth-client" }
clap = { version = "4.5.26", features = ["derive"] }
tracing = "0.1.41"
csv = "1.3.1"
serde = "1.0.217"
