[package]
name = "zkvm-benchmarks-eval"
version = "0.0.1"
edition = "2021"

[build-dependencies]
vergen-git2 = { version = "1.0.0", features = ["build"] }


[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
