[package]
name = "zkvm-benchmarks-eval"
version = "0.0.1"
edition = "2021"

[build-dependencies]
vergen-git2 = { version = "1.0.0", features = ["build"] }


[dependencies]
reth-client = { path = "../reth-client" }
block-downloader = { path = "../block-downloader" }
clap = { version = "4.5.26", features = ["derive"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.18"
csv = "1.3.1"
serde = "1.0.217"
risc0-zkvm = { version = "1.2.1", features = ["prove"] }
bincode = "1.3.3"
eyre = "0.6.12"
url = "2.5.4"
tokio = { version = "1.43.0", features = ["rt", "rt-multi-thread", "macros"] }
