[package]
name = "zkvm-benchmarks-eval"
version.workspace = true
edition.workspace = true

[build-dependencies]
vergen-git2 = { version = "1.0.0", features = ["build"] }

[dependencies]
alloy-provider.workspace = true
bincode.workspace = true
serde_json.workspace = true
clap.workspace = true
csv = "1.3.1"
eyre.workspace = true
serde.workspace = true
tokio.workspace = true
tracing-subscriber.workspace = true
tracing.workspace = true
url.workspace = true

# workspace
reth-client.workspace = true
block-downloader.workspace = true

# zk
risc0-zkvm = { version = "1.2.1", features = ["prove"] }

[features]
risc0 = []
